/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Button": "Refresh",
    "currentTrainedAdslModeLabel": "Current trained adsl mode",
    "currentTrainedAdslPathLabel": "Current trained adsl path",
    "currentTrainingStatusLabel": "Current training status",
    "Done": "Done",
    "downstreamAttenuationLabel2": "Downstream attenuation",
    "downstreamAttenuationValue": "NA",
    "downstreamBitRateLabel": "Downstream bit rate",
    "downstreamBitRateLabel1": "Downstream noise margin",
    "downstreamBitRateLabel2": "Downstream bit rate",
    "downstreamBitRateLabel3": "Downstream bit rate",
    "downstreamBitRateLabel4": "Downstream bit rate",
    "downstreamBitRateLabel5": "Upstream bit rate",
    "downstreamBitRateLabel6": "Current trained adsl mode",
    "downstreamBitRateLabel7": "Current training status",
    "downstreamBitRateLabel8": "Current trained adsl path",
    "downstreamBitRateValue": "NA",
    "downstreamBitRateValue1": "NA",
    "downstreamBitRateValue2": "NA",
    "downstreamBitRateValue3": "NA",
    "downstreamBitRateValue4": "NA",
    "downstreamBitRateValue5": "NA",
    "downstreamBitRateValue6": "NA",
    "downstreamBitRateValue7": "NA",
    "downstreamBitRateValue8": "NA",
    "downstreamNoiseMarginLabel": "Downstream noise margin",
    "downstreamNoiseMarginValue": "NA",
    "Hello, World!": "Downstream bit rate",
    "Hello, World!1": "Downstream bit rate",
    "modeValue": "NA",
    "statusValue": "NA",
    "trainedPathValue": "NA",
    "upstreamAttenuationLabel": "Upstream noise margin",
    "upstreamAttenuationValue": "NA",
    "upstreamBitRateLabel": "Upstream bit rate",
    "upstreamBitRateValue": "NA",
    "upstreamNoiseMarginLabel": "Upstream noise margin",
    "upstreamNoiseMarginValue": "NA"
};

